### ISSUE TITLE
[Bug]: Esbuild install error

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [CoderLine/mocha-vscode#168]
### Checklist

- [X] I have read and agree to the [Code of Conduct](https://github.com/CoderLine/mocha-vscode/blob/main/code-of-conduct.md)
- [X] I have searched for [related issues](https://github.com/CoderLine/mocha-vscode/issues) and [discussions](https://github.com/CoderLine/mocha-vscode/discussions) but they did not match this problem.
- [ ] I want to contribute a bugfix myself.

### Actual behavior

Can't start extension

### Expected behavior

Extension start successfully

### Minimal, Reproducible Example

https://github.com/muhammadyusuf-kurbonov/mocha-forVSCode-bug-example

### Output

Extension host:
```
2024-10-16 11:39:59.566 [error] Error: ENOENT: no such file or directory, rename '/home/muhammadyusuf-kurbonov/.vscode/extensions/coderline.mocha-vscode-1.2.3/tmp/package' -> '/home/muhammadyusuf-kurbonov/.vscode/extensions/coderline.mocha-vscode-1.2.3/node_modules/@esbuild/linux-x64'
	at async Object.rename (node:internal/fs/promises:784:10)
	at async vKe (/home/muhammadyusuf-kurbonov/.vscode/extensions/coderline.mocha-vscode-1.2.3/out/extension.js:587:54595)
	at async /home/muhammadyusuf-kurbonov/.vscode/extensions/coderline.mocha-vscode-1.2.3/out/extension.js:614:18395
```

### Plugin Version Details

Name: Mocha for VS Code
Id: coderline.mocha-vscode
Description: Run and debug Mocha tests right within VS Code.
Version: 1.2.3
Publisher: CoderLine
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=coderline.mocha-vscode

### VS Code Version Details

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.10.12-200.fc40.x86_64

**Comment by Danielku15** [comment]
Sorry for the repeating problems. The ESBuild installation seems quite a sensitive area. I added some new integration tests using a packed version of the extension. Some errors were not caught by the tests when executing tests on the working directory.
