### ISSUE TITLE
[Bug]:  Can not run test unless `checkJs`: false

### ISSUE THREAD

**Issue by marcus-pousette** [CoderLine/mocha-vscode#23]
### Checklist

- [does not exist] I have read and agree to the [Code of Conduct](code-of-conduct)
- [X] I have searched for [related issues](https://github.com/CoderLine/mocha-vscode/issues) and [discussions](https://github.com/CoderLine/mocha-vscode/discussions) but they did not match this problem.
- [X] I want to contribute a bugfix myself.

### Actual behavior

Node v18.12.0

.mocharc.js 
```json
{
  "require": [
    "ts-node/register"
  ],
  "node-option": [
    "experimental-specifier-resolution=node",
    "loader=ts-node/esm",
    "no-warnings"
  ],
  "extensions": [
    "ts"
  ],
  "spec": [
    "**/test/**/*.spec.ts",
    "**/docs/**/*.spec.ts"
  ],
  "watch-files": [
    "src",
    "modules",
    "examples"
  ],
  "ignore": [
    "**/node_modules/**",
    "**/dist/**"
  ],
  "timeout": "10000"
}
```
tsconfig.json
```json
{
	"compilerOptions": {
	"strict": true,
        "outDir": "dist",
        "allowJs": true,
        "checkJs": true,
        "target": "ES2022",
        "module": "ES2022"
	}
}
```
Get output 

```
✖ ERROR: TypeError: Could not load reporter "/Users/admin/git/mocha-vscode/out/reporter/fullJsonStreamReporter.js":

 ../mocha-vscode/out/reporter/fullJsonStreamReporter.js(7,20): error TS7006: Parameter 'to' implicitly has an 'any' type.
 ```

### Expected behavior

Test are running successfully 

### Minimal, Reproducible Example

Use provided mocharc.json and tsconfig.json and try to debug or run a test

### Output

`
✖ ERROR: TypeError: Could not load reporter "/Users/admin/git/mocha-vscode/out/reporter/fullJsonStreamReporter.js":

 ../mocha-vscode/out/reporter/fullJsonStreamReporter.js(7,20): error TS7006: Parameter 'to' implicitly has an 'any' type.
 `

### Plugin Version Details

131c2c66f099991c98bfdb76fd09e0b996abde66

### VS Code Version Details

1.87.0
019f4d1419fbc8219a181fab7892ebccf7ee29a2
arm64

### Further details

This might be a configuration issue but I have not yet found good options to circumvent this. Also tried to recompile this extensions with typings for the reporter but that did not help either

**Comment by Danielku15** [comment]
Thanks for reporting. The problem should be gone now through 2 improvements: 

1. For the fully built and installed plugin (vsix) the Mocha reporter is copied to the node_modules folder. By this it is excluded by many defaults to not be checked anymore. This change is anyhow needed for shipping the extension without an own Mocha version. 
2. I also added a `// @ts-nocheck` to the output files which prevents the reporter to be checked by the TypeScript compiler when loaded by ts-node.
