### ISSUE TITLE
[Feature Request]: Publish extension on OpenVSX

### ISSUE THREAD

**Issue by jirutka** [CoderLine/mocha-vscode#79]
### Description

Can you please also publish this extension on [OpenVSX](https://open-vsx.org/) to make it accessible for [VSCodium](https://vscodium.com/) users?

See [How to publish an extension](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension).

**Comment by Danielku15** [comment]
Sorry for the delay on that matter. I'm working on getting all accounts and approvals to publish extensions on OpenVSX, once these things are through, I can publish the releases to OpenVSX.

**Comment by Danielku15** [comment]
https://open-vsx.org/extension/coderline/mocha-vscode Done 🥳
